defaultTasks 'clean', 'test', 'aggregate'

buildscript {
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:3.3.10"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.serenity-gradle-plugin'

group = 'org.automation.appium'
version = '1.0-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '3.3.10'
    junitVersion = '4.13.2'
    cucumberVersion = '7.11.2'
    appiumVersion = '8.5.1'
}

dependencies {
    implementation "ch.qos.logback:logback-classic:1.2.10"

    // Serenity
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-ensure:${serenityVersion}"

    // Appium
    testImplementation "io.appium:java-client:${appiumVersion}"

    // JUnit 4
    testImplementation "junit:junit:${junitVersion}"

    // Cucumber
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit:${cucumberVersion}"
}

test {
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

serenity {
    testRoot = "org.automation.appium" // Asegúrate de que esto sea tu paquete raíz real
    requirementsDir = "src/test/resources/features"
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)
