defaultTasks 'clean', 'test', 'aggregate'

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:5.3.9"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.serenity-gradle-plugin'

group = 'org.automation.appium'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '5.3.9'
    cucumberVersion = '7.34.2'
    appiumVersion = '10.0.0'
}

dependencies {

    implementation "ch.qos.logback:logback-classic:1.5.18"

    // Serenity
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-ensure:${serenityVersion}"

    // Appium
    testImplementation "io.appium:java-client:${appiumVersion}"

    // Cucumber
    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit-platform-engine:${cucumberVersion}"
    testImplementation "org.junit.platform:junit-platform-suite:1.12.2"
}

test {
    useJUnitPlatform()

    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

serenity {
    testRoot = "org.automation.appium"
    requirementsDir = "src/test/resources/features"
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)