webdriver.driver=appium

appium.hub=http://127.0.0.1:4723

appium.platformName=Android
appium.platformVersion=13.0
appium.deviceName=emulator-5554
appium.automationName=UiAutomator2
appium.udid=emulator-5554

appium.app=C:/Users/Usuario/Documents/PROYECTOS/appium-serenitybdd-screenplay/src/test/resources/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
appium.appPackage=com.swaglabsmobileapp
appium.appActivity=com.swaglabsmobileapp.MainActivity

appium.autoGrantPermissions=true
appium.newCommandTimeout=1000

serenity.outputDirectory=target/site/serenity
serenity.take.screenshots=FOR_FAILURES
webdriver.wait.for.timeout=10000