# Nombre del proyecto
serenity.project.name = Appium-SerenityBDD-Screenplay

# Carpeta base para los tests
serenity.test.root = org.automation.appium

# Ruta donde se generarán los reportes
serenity.outputDirectory = target/site/serenity

# Tipos de reporte a generar
serenity.reports = json, single-page-html

# Mostrar más detalle en los pasos
serenity.report.show.full.test.name = true
serenity.report.show.manual.tests=true
serenity.report.show.step.details = true
serenity.take.screenshots=FOR_FAILURES

# Logging detallado (opcional)
serenity.verbose.logging = true

# Tiempo de espera estándar para acciones
webdriver.wait.for.timeout = 10000

# Versión de navegador (si aplica para otros test web)
webdriver.driver = appium